spring:
  main:
    banner-mode: off
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
  config:
    import:
      - optional:file:.env[.properties]
  data:
    neo4j:
      database: ${NEO4J_DATABASE}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

logging:
  level:
    root: OFF

xml:
  validation:
    enabled: ${XML_VALIDATION_ENABLED}
    schema:
      path: ${XSD_SCHEMA_LOCATION}
  delimiter: ;
  script:
    path: ${XML_CONFIG_LOCATION}